from tg_bot_base.message import Message as BaseMessage
from ...message import SentMessage as BaseSentMessage

class SentMessage(BaseSentMessage):
    def __init__(self): ...
    
    async def edit(self, user_id: int): ...
    
    async def delete(self, user_id: int): ...
    
    def __eq__(self, other: "Message"): ...
    
    def clone(self): ...

class Message(BaseMessage):
    def __init__(self): ...

    async def send(self, user_id: int): ...
    
    def __eq__(self, other: "Message"): ...
    
    def clone(self): ...



class AudioMessage(Message): ...

class DocumentMessage(Message): ...

class SimpleMessage(Message): ...

class PhotoMessage(Message): ...

class VideoMessage(Message): ...

class VideoNoteMessage(Message): ...


class SentAudioMessage(Message): ...

class SentDocumentMessage(Message): ...

class SentSimpleMessage(Message): ...

class SentPhotoMessage(Message): ...

class SentVideoMessage(Message): ...

class SentVideoNoteMessage(Message): ...